name: Deploy Astro to Hostinger (SFTP)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# Evita que se crucen dos deploys al mismo tiempo
concurrency:
  group: deploy-astro-hostinger
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Astro
        run: npm run build

      # Sube SOLO el contenido de dist/ a la raíz pública del dominio
      - name: Deploy to Hostinger via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: 'dist/*'  # contenido, no la carpeta
          remote_path: 'domains/elmeromeroabarrotero.com/public_html'
          delete_remote_files: true   # ponlo en false si NO quieres limpieza
          args: "-o StrictHostKeyChecking=no"
